# Environment: development
# Use envsubst to replace the parameters in the environment block

# Use ports > 3000 for any deployed software

services:
  credstack:
    image: gitea.prod02.asgard-server.net/odin/credstack-api/credstack-api:dev-latest
    container_name: dev-credstack-api
    environment:
      - CREDSTACK_MONGO_HOSTNAME=${MONGO_HOSTNAME}
      - CREDSTACK_MONGO_PORT=${MONGO_PORT}
      - CREDSTACK_MONGO_USE_AUTHENTICATION=${MONGO_USE_AUTHENTICATION}
      - CREDSTACK_MONGO_AUTHENTICATION_DATABASE=${MONGO_AUTHENTICATION_DATABASE}
      - CREDSTACK_MONGO_USERNAME=${MONGO_USERNAME}
      - CREDSTACK_MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - "/home/odin/volumes/credstack/logs:/var/log/credstack"
    ports:
      - "3001:8080"
    restart: unless-stopped
