name: Development
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Go-Lang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          cache: false

      - name: Unit tests go here
        run: echo "unit tests go here"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{secrets.REGISTRY}}
          username: ${{secrets.REGISTRY_USER}}
          password: ${{secrets.REGISTRY_TOKEN}}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{secrets.REGISTRY_TAG}}/credstack-api:dev-latest, ${{secrets.REGISTRY_TAG}}/credstack-api:dev-${{env.GITHUB_SHA}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1.2.0

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{secrets.REGISTRY}}
          username: ${{secrets.REGISTRY_USER}}
          password: ${{secrets.REGISTRY_TOKEN}}

      - name: Transform docker compose
        env:
          MONGO_HOSTNAME: ${{vars.MONGO_HOSTNAME}}
          MONGO_PORT: ${{vars.MONGO_PORT}}
          MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
          MONGO_PASSWORD: ${{vars.MONGO_PASSWORD}}
          MONGO_USE_AUTHENTICATION: ${{vars.MONGO_USE_AUTHENTICATION}}
          MONGO_AUTHENTICATION_DATABASE: ${{vars.MONGO_AUTHENTICATION_DATABASE}}
        run: |
          apt-get update && apt-get install gettext -y
          envsubst < dev.docker-compose.yml > docker-compose.yml

      - name: Stop existing containers
        run: docker compose -p deploy02 down

      - name: Pull dev-latest
        run: docker compose -f docker-compose.yml pull

      - name: Deploy
        run: docker compose -p deploy02 -f docker-compose.yml up -d
